# HeidiSQL Dump 
#
# --------------------------------------------------------
# Host:                 127.0.0.1
# Database:             newsinfo
# Server version:       5.4.3-beta-community
# Server OS:            Win32
# Target-Compatibility: Standard ANSI SQL
# HeidiSQL version:     3.1 RC1 Revision: 1064
# --------------------------------------------------------

/*!40100 SET CHARACTER SET latin1;*/
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ANSI';*/
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;*/


#
# Database structure for database 'newsinfo'
#

CREATE DATABASE /*!32312 IF NOT EXISTS*/ "newsinfo" /*!40100 DEFAULT CHARACTER SET utf8 COLLATE utf8_bin */;

USE "newsinfo";


#
# Table structure for table 'api_news'
#

CREATE TABLE /*!32312 IF NOT EXISTS*/ "api_news" (
  "id" int(11) NOT NULL AUTO_INCREMENT,
  "source" varchar(50) NOT NULL,
  "title" varchar(255) NOT NULL,
  "description" text,
  "url" varchar(255) DEFAULT NULL,
  "image_url" varchar(255) DEFAULT NULL,
  "published_at" datetime DEFAULT NULL,
  "category" varchar(50) DEFAULT NULL,
  "fetched_at" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY ("id")
) AUTO_INCREMENT=118 /*!40100 DEFAULT CHARSET=utf8 COLLATE=utf8_bin*/;



#
# Dumping data for table 'api_news'
#

/*!40000 ALTER TABLE "api_news" DISABLE KEYS;*/
LOCK TABLES "api_news" WRITE;
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(8,'CNN','An oil giant’s $300 million case against Greenpeace is ending. The outcome could have chilling impacts on free speech','The environmental groups is being sued over anti-pipeline protests nearly a decade ago. What’s decided here could have wide ranging impacts on protest in the US','https://www.cnn.com/2025/03/18/climate/greenpeace-lawsuit-first-amendment/index.html','https://media.cnn.com/api/v1/images/stellar/prod/gettyimages-1232057617.jpg?c=16x9&q=w_800,c_fill','2025-03-18 13:59:27','General','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(9,'CNN','Angry voters confront GOP lawmaker at town hall in Washington | CNN Politics','Rep. Michael Baumgartner (R-WA) faced a hostile crowd at a town hall in Spokane, Washington. Many voters were upset about President Trump’s actions during his first months in office.','https://www.cnn.com/2025/03/18/politics/video/michael-baumgartner-town-hall-trump-spokane-digvid','https://media.cnn.com/api/v1/images/stellar/prod/still-21468841-1582706-435-still.jpg?c=16x9&q=w_800,c_fill','2025-03-18 12:13:44','Politics','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(10,'CNN','Could humans live underwater? UK startup DEEP thinks so | CNN Business','Humans living underwater. It might sound like something from a science fiction movie, but this is the real ambition of UK startup DEEP. CNN’s Max Foster takes a tour of its Sentinel habitat to find out why the company believes it will be housing people underw…','https://www.cnn.com/2025/03/18/business/video/humans-living-underwater-deep-startup-ldn-digvid','https://media.cnn.com/api/v1/images/stellar/prod/sentinel-seafloor-scene.jpg?c=16x9&q=w_800,c_fill','2025-03-18 10:49:58','Business','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(11,'CNN','Welcome back to Earth: Say goodbye to blurry eyes, puffy faces, ‘chicken legs’ and a little extra height','Down to their very DNA, astronauts’ bodies can change in weird and sometimes significant ways, particularly during a long flight high above the Earth: They start to elongate, often developing a taller “space height” and because human bodies are mostly liquid,…','https://www.cnn.com/2025/03/18/health/space-physical-effects-astronauts-bodies/index.html','https://media.cnn.com/api/v1/images/stellar/prod/astronauts-in-space-1.jpg?c=16x9&q=w_800,c_fill','2025-03-18 10:00:52','Health','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(12,'CNN','Parents of Sudiksha Konanki ask authorities to declare her dead as last man seen with missing student seeks freedom in court','The parents of missing US college student Sudiksha Konanki are asking authorities in the Dominican Republic that she be officially declared dead, nearly two weeks after she went missing while on spring break in Punta Cana.','https://www.cnn.com/2025/03/18/us/sudiksha-konanki-missing-student-punta-cana-tuesday/index.html','https://media.cnn.com/api/v1/images/stellar/prod/2025-03-13t223157z-1011997508-rc2ecdatmscx-rtrmadp-3-dominican-republic-missing-tourist.jpg?c=16x9&q=w_800,c_fill','2025-03-18 07:50:33','General','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(13,'CNN','Comedian Tracy Morgan appears to fall ill during Knicks game at Madison Square Garden','Tracy Morgan, the comedian and actor celebrated for his roles on “30 Rock” and “Saturday Night Live,” appeared to fall ill while sitting courtside at Monday night’s matchup between the New York Knicks and the Miami Heat at Madison Square Garden. The incident …','https://www.cnn.com/2025/03/18/entertainment/tracy-morgan-sick-knicks-madison-square-garden-hnk/index.html','https://media.cnn.com/api/v1/images/stellar/prod/gettyimages-2200060368.jpg?c=16x9&q=w_800,c_fill','2025-03-18 05:34:34','Entertainment','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(14,'CNN','NASA’s Suni Williams and Butch Wilmore are finally returning home after nine months in space','NASA astronauts Butch Wilmore and Suni Williams set out for a weeklong mission at the International Space Station last year. After nine months, they are coming home.','https://www.cnn.com/2025/03/18/science/spacex-crew-9-astronauts-space/index.html','https://media.cnn.com/api/v1/images/stellar/prod/screenshot-2025-03-18-at-1-13-22-pm.jpg?c=16x9&q=w_800,c_fill','2025-03-18 04:07:17','General','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(15,'CNN','Video shows missing college student at hotel bar | CNN','New surveillance video shows missing US college student hours before she was reported missing. In the video, 20-year-old Sudiksha Konanki is seen with her friends and the last known person to see her, 22-year-old Joshua Riibe, at a bar at the Riu República Ho…','https://www.cnn.com/2025/03/17/world/video/missing-college-student-sudiksha-konanki-hotel-bar-surveillance-video-digvid','https://media.cnn.com/api/v1/images/stellar/prod/02-konanki-missing.jpg?c=16x9&q=w_800,c_fill','2025-03-18 00:26:12','General','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(16,'CNN','Harvard announces it will go tuition-free for students from families making $200,000 or less','Harvard undergraduate tuition will be free for students from families making $200,000 or less, starting next fall, the university announced Monday in its latest effort to provide an Ivy League education to those who might otherwise be priced out.','https://www.cnn.com/2025/03/17/us/harvard-tuition-free-families-income/index.html','https://media.cnn.com/api/v1/images/stellar/prod/ap25058655463857.jpg?c=16x9&q=w_800,c_fill','2025-03-17 23:50:31','General','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(17,'CNN','Deported Brown University doctor acknowledged she attended Hezbollah leader’s funeral on visit to Lebanon, source says','A Brown University assistant professor and doctor was deported over the weekend from Boston to Lebanon after federal agents found photos of Hezbollah leader Hassan Nasrallah and Iran’s supreme leader on her cell phone, a source familiar with the case told CNN.','https://www.cnn.com/2025/03/17/us/brown-university-doctor-deported-hnk/index.html','https://media.cnn.com/api/v1/images/stellar/prod/gettyimages-1289255435.jpg?c=16x9&q=w_800,c_fill','2025-03-17 05:16:39','General','2025-03-19 20:52:56');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(18,'NDTV News','Ghaziabad Man Rapes, Strangles 7-Year-Old Daughter, Blames Neighbour: Cops','A man allegedly raped and strangled his seven-year-old daughter in the Loni Border area, later fabricating a story to frame a neighbour, police said on Tuesday.','https://www.ndtv.com/india-news/ghaziabad-man-rapes-strangles-7-year-old-daughter-blames-neighbour-cops-7953625','https://c.ndtvimg.com/2022-12/0htt5beg_india-police-generic_625x300_23_December_22.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 15:16:23','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(19,'NDTV News','IPL 2025: Sunrisers Hyderabad SWOT Analysis And Strongest Playing XI','With a power-packed batting lineup, Sunrisers Hyderabad (SRH) look one of the favourites to make the IPL 2025 playoffs.','https://sports.ndtv.com/ipl-2025/ipl-2025-sunrisers-hyderabad-swot-analysis-and-strongest-playing-xi-srh-squad-7953570','https://c.ndtvimg.com/2024-05/nfduivn_travis-head-abhishek-sharma-bcci_625x300_08_May_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 15:10:16','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(20,'NDTV News','Return To Fighting In Gaza ''Fully Coordinated With Washington'': Israel','Israeli government spokesman David Mencer said Tuesday that the country&#039;s return to fighting in Gaza had been &quot;fully coordinated with Washington&quot; following the deadliest strikes on the territory since a fragile ceasefire took effect in January.','https://www.ndtv.com/world-news/israel-gaza-airstrikes-hamas-hostages-washington-us-7953558','https://c.ndtvimg.com/2025-03/f5i31iso_israel-gaza-war_625x300_18_March_25.jpeg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 15:09:20','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(21,'NDTV News','Trump-Putin Talks On Ending Russia-Ukraine War Going Well: White House','US President Donald Trump today dialled his Russian counterpart Vladimir Putin in an attempt to find an end to the war in Ukraine.','https://www.ndtv.com/world-news/donald-trump-dials-vladimir-putin-to-discuss-ending-russia-ukraine-war-7953557','https://i.ndtvimg.com/i/2017-06/donald-trump-phone-afp-650_650x400_51498634686.jpg','2025-03-18 15:09:01','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(22,'NDTV News','Trade Marks Registry Accepts ''Chutiyaram'' For Biscuits Company, Does U-Turn','Two weeks after it accepted an application for the registration of the word &#039;Chutiyaram&#039;, making many wonder whether it was in keeping with a section barring trademarks that are considered obscene, the Trade Marks Registry has done a U-turn.','https://www.ndtv.com/india-news/trademark-namkeen-trade-marks-registry-accepts-chutiyaram-for-biscuits-company-does-u-turn-7953341','https://c.ndtvimg.com/2019-06/q43s9bf8_biscuits-generic_625x300_29_June_19.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 14:39:17','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(23,'NDTV News','NASA''s Webb Captures First Images Of Carbon Dioxide Outside Solar System','This finding provides compelling evidence that the giant planets in HR 8799 formed through core accretion, a process similar to the formation of Jupiter and Saturn.','https://www.ndtv.com/science/nasas-webb-captures-first-direct-images-of-carbon-dioxide-outside-solar-system-7953251','https://c.ndtvimg.com/2025-03/a2cgrjko_carbon-dioxide-outside-our-solar-system_625x300_18_March_25.jpeg','2025-03-18 14:27:51','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(24,'NDTV News','Uddhav Thackeray Bowed Before PM Modi: Eknath Shinde''s Big Claim','Former Chief Minister of Maharashtra Uddhav Thackeray had bowed down before Prime Minister Narendra Modi, asking to be saved from the action of investigating agencies, Deputy Chief Minister Eknath Shinde has claimed.','https://www.ndtv.com/india-news/uddhav-thackeray-bowed-before-pm-modi-eknath-shindes-big-claim-7953248','https://c.ndtvimg.com/2025-01/9jtvek6g_uddhav-thackeray-eknath-shinde_625x300_22_January_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 14:27:33','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(25,'NDTV News','Fake Blood, Sharp Weapon: Reel Shoot Sparks Panic In Karnataka, 2 Arrested','An attempt to film a murder scene for an Instagram reel triggered panic in Karnataka&#039;s Kalaburagi late on Monday, police on Tuesday said, adding that two people have been arrested.','https://www.ndtv.com/india-news/fake-blood-sharp-weapon-instagram-reel-shoot-sparks-panic-in-karnataka-kalaburagi-humnabad-ring-road-men-arrested-7953230','https://c.ndtvimg.com/2025-03/occg0ia_instagram-reel-photo_625x300_18_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 14:23:05','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(26,'NDTV News','BCCI''s Fresh Twist After Kohli''s ''Family Diktat'' Outburst - Report Explains','The Board of Control for Cricket in India (BCCI) may consider making changes to the ''family diktat'' introduced after the Test series defeat against Australia, according to a report.','https://sports.ndtv.com/cricket/bcci-to-rethink-family-diktat-after-virat-kohli-criticism-report-makes-big-claim-7953042','https://c.ndtvimg.com/2025-03/7bisv48o_virat-kohli-anushka-sharma-cute-moments_650x400_11_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 14:00:21','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(27,'NDTV News','Honda Activa e, QC 1 Official Accessories Revealed: Check Prices','HMSI&#039;s first-ever electric two-wheelers are gearing up to reach the customers. Here&#039;s what you get with the Activa e: and QC1 as accessories.','https://www.ndtv.com/auto/honda-activa-e-qc-1-official-accessories-revealed-check-prices-7952995','https://c.ndtvimg.com/2025-03/oqrrg1v8_honda-accessopries_625x300_18_March_25.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=800','2025-03-18 13:54:59','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(28,'NDTV News','Using Only YouTube For Training, Kerala Woman Reaches Everest Base Camp','Ms Cheruveettil dedicated over four months to meticulous self-preparation for her journey.','https://www.ndtv.com/india-news/with-no-formal-training-59-year-old-kerala-tailor-reaches-everest-base-camp-with-youtube-tips-7952992','https://c.ndtvimg.com/2025-03/1ukk5fug_vasanthi-cheruveettil_625x300_18_March_25.jpeg','2025-03-18 13:53:52','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(29,'NDTV News','"No Such Data Maintained Centrally": Home Ministry On Maha Kumbh Deaths','Six weeks after the Maha Kumbh stampede, the Home Ministry has told the Lok Sabha the centre did not conduct an inquiry of its own and does not have data on the number of dead and injured.','https://www.ndtv.com/india-news/maha-kumbh-stampede-death-toll-no-such-data-maintained-centrally-home-ministry-on-maha-kumbh-deaths-7952905','https://c.ndtvimg.com/2025-01/bl6dvug8_maha-kumbh-stampede_625x300_29_January_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 13:41:51','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(30,'NDTV News','Samosas And The Risk Of Private Spacecraft: What Sunita Williams Had Told NDTV','Eight years before the Boeing Starliner suffered glitches, leaving her stranded on the International Space Station for nine months, NDTV had spoken to Sunita Williams and asked whether she thought flying on a privately built spacecraft could be risky','https://www.ndtv.com/india-news/iss-crew-9-boeing-starliner-nasa-spacex-samosas-and-the-risk-of-private-spacecraft-what-sunita-williams-told-ndtv-in-2016-7952828','https://c.ndtvimg.com/2025-03/5fob3eqo_sunita-williams-2016-interview_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 13:41:08','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(31,'NDTV News','Updated Suzuki GSX-8S, GSX-S1000GT Unveiled; Check Details','Suzuki has recently unvieled a few updates for the GSX-8S and the GSX-S1000GT. Check out to learn more.','https://www.ndtv.com/auto/updated-suzuki-gsx-8s-gsx-s1000gt-unveiled-check-details-7952799','https://c.ndtvimg.com/2025-03/rh68053o_suzuki-bikes_625x300_18_March_25.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=800','2025-03-18 13:30:11','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(32,'NDTV News','RCB Face Major Allegations Just Ahead Of IPL 2025: "No Camaraderie..."','Former Royal Challengers Bengaluru spinner Shadab Jakati opened up about why he believes the franchise has not won a single Indian Premier League (IPL) trophy till now.','https://sports.ndtv.com/ipl-2025/ex-csk-chennai-super-kings-stars-big-allegations-against-royal-challengers-bengaluru-rcb-ahead-of-ipl-2025-focus-on-7951325','https://c.ndtvimg.com/2025-03/8977dt0g_cs_625x300_18_March_25.jpeg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 13:29:37','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(33,'NDTV News','6 Supreme Court Judges To Visit Manipur''s Relief Camps, Meet Displaced People','Six Supreme Court judges will visit relief camps where internally displaced people are living in Manipur on March 22 &quot;to strengthen legal and humanitarian support&quot; in the crisis-hit state, the National Legal Services Authority (NALSA) said.','https://www.ndtv.com/india-news/6-supreme-court-judges-to-visit-manipur-relief-camps-meet-displaced-people-7952774','https://c.ndtvimg.com/2024-02/4l5tjo58_manipur-generic_625x300_28_February_24.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 13:26:37','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(34,'NDTV News','Hamas Chose War By Refusing To Release Hostages: White House','The United States said Tuesday that Hamas had chosen war by refusing to release hostages, as Israel unleashed its most intense strikes since a ceasefire and vowed to continue fighting until all hostages are returned.','https://www.ndtv.com/world-news/israel-gaza-airstrikes-hamas-chose-war-by-refusing-to-release-hostages-white-house-7952766','https://c.ndtvimg.com/2025-01/453n6qd_white-house_625x300_08_January_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 13:24:57','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(35,'NDTV News','Bhagyashree Shares Easy Maharashtrian Recipe For Gavar Phali','Bhagyashree recently spoke about the benefits of cluster beans or Gavar Phali in an Instagram post. She also shared a simple way to cook them.','https://food.ndtv.com/news/bhagyashree-shares-easy-maharashtrian-recipe-for-gavar-phali-watch-video-here-7952764','https://c.ndtvimg.com/2024-07/9dmma35g_bhagyashree_625x300_31_July_24.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=675','2025-03-18 13:24:25','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(36,'NDTV News','Poll Body, UIDAI To Hold Technical Consultations On Aadhaar-Voter ID Link','The EC on Tuesday said linkage of voter cards with Aadhaar would be done according to the prevailing law and the Supreme Court&#039;s directions and added technical consultations between UIDAI and its experts for the exercise would &quot;begin soon&quot;.','https://www.ndtv.com/india-news/poll-body-uidai-to-hold-technical-consultations-on-aadhaar-voter-id-link-7952701','https://c.ndtvimg.com/2023-07/jgvnjvf8_aadhaar-generic_625x300_22_July_23.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 13:18:29','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(37,'NDTV News','De Villiers Reveals Virat''s Text Over Famous RCB Chant: "Bit Of Trouble..."','Legendary South Africa cricket team star AB De Villiers revealed that his former Royal Challengers Bengaluru (RCB) teammate Virat Kohli asked him to not say ''Ee sala cup namde''.','https://sports.ndtv.com/ipl-2025/ab-de-villiers-reveals-virat-kohlis-text-over-famous-royal-challengers-bengaluru-rcb-chant-bit-of-trouble-7951958','https://c.ndtvimg.com/2021-04/gkec88q_virat-kohli-ab-de-villiers-hug-bcciipl_650x400_16_April_21.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 13:10:50','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(38,'NDTV News','Opinion: Isn''t Revanth Reddy Crossing The Line?','Women, and often men, being stripped and paraded is a depressingly familiar headline in India. In religion, caste, or family conflicts, a woman&#039;s body becomes the metaphor for the &quot;honour&quot; of an entire community, caste, and clan.','https://www.ndtv.com/opinion/isnt-revanth-reddy-crossing-the-line-7952617','https://c.ndtvimg.com/2025-02/ljvis7dg_revanth-reddy_625x300_15_February_25.jpeg','2025-03-18 13:07:41','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(39,'NDTV News','BCCI Set To Take Major Decision On Tobacco And Crypto Company Sponsorships','The BCCI will form the organising committee of the Women''s ODI World Cup besides taking a call on the venues for the ICC event it will be hosting later this year at its Apex Council emergent meeting in Kolkata on March 22.','https://sports.ndtv.com/cricket/bcci-set-to-take-major-decision-on-tobacco-and-crypto-company-sponsorships-7952057','https://c.ndtvimg.com/2021-09/f6mh8i18_bcci-logo_625x300_20_September_21.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 13:06:32','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(40,'NDTV News','Bengaluru Techie With Rs 1.5 Lakh Salary Struggles To Sustain Family','His post struck a chord with numerous young professionals, sparking a broader discussion about the harsh realities of urban living, financial insecurity, and the true cost of chasing one&#039;s dreams.','https://www.ndtv.com/feature/bengaluru-techie-with-rs-1-5-lakh-a-month-struggles-to-sustain-family-everything-is-super-inflated-7952582','https://c.ndtvimg.com/2025-03/c768a4dg_bengaluru_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 13:03:04','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(41,'NDTV News','Had ''No Alternative'' To Resuming Gaza Operations: Israel After Airstrikes','Foreign Minister Gideon Saar said Tuesday that Israel had &quot;no alternative&quot; other than to resume military operations in Gaza after its efforts to secure the release of hostages failed.','https://www.ndtv.com/world-news/israel-gaza-airstrikes-hamas-hostages-7952527','https://c.ndtvimg.com/2025-03/vjg5265_israel-gaza-war_625x300_18_March_25.jpeg','2025-03-18 12:57:07','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(42,'NDTV News','Indian Runner Archana Jadhav Handed 4-Year Ban For Failed Dope Test','According to World Athletics'' Athletes Integrity Unit (AIU), sprinter Archana Jadhav''s sample contained prohibited substance Oxandrolone.','https://sports.ndtv.com/athletics/indian-runner-archana-jadhav-handed-four-year-ban-for-failed-dope-test-7951506','https://c.ndtvimg.com/2025-03/76oj97pg_archana-jadhav_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:56:10','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(43,'NDTV News','Committed To Bring Normalcy In Manipur, Says Nirmala Sitharaman','Finance Minister Nirmala Sitharaman on Tuesday said the central government is committed to bringing normalcy to Manipur and assured all support for the economic growth of the state.','https://www.ndtv.com/india-news/committed-to-bring-normalcy-in-manipur-says-nirmala-sitharaman-7952486','https://c.ndtvimg.com/2025-02/0108fdmo_nirmala-sitharaman_625x300_11_February_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:51:16','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(44,'NDTV News','''Pant Has Our 100% Support'': Pooran''s Big Statement Ahead Of IPL 2025','Nicholas Pooran has showered support to new Lucknow Super Giants (LSG) captain Rishabh Pant adding that the franchise has a balanced squad to lift the title in the upcoming Indian Premier League (IPL) 2025 season.','https://sports.ndtv.com/ipl-2025/rishabh-pant-has-our-100-support-nicholas-poorans-big-statement-ahead-of-ipl-2025-7952075','https://c.ndtvimg.com/2025-03/ol7ljks8_rishabh-pant_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:42:10','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(45,'NDTV News','7 Game-Changing Tips For A Smooth First Cruise Experience','Your first cruise vacation is guaranteed to be an unforgettable experience, but a little planning goes a long way.','https://www.ndtv.com/travel/essential-tips-for-first-cruise-7952354','https://c.ndtvimg.com/2025-03/2vt5sqg8_cruise_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:35:38','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(46,'NDTV News','Video: Fire Breaks Out Near Oil Depot In Jharkhand, Village Evacuated','A massive fire broke out near an Indian Oil Terminal in Jharkhand&#039;s Devghar today. People from the nearby village have been evacuated and a goods and passenger train at the Jasidh station - located close to the spot - have been moved away.','https://www.ndtv.com/india-news/video-fire-breaks-out-near-indian-oil-depot-in-jharkhand-village-evacuated-7952338','https://c.ndtvimg.com/2025-03/6erp4thg_jharkhand-fire_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:32:08','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(47,'NDTV News','All Eyes On Chhetri''s Comeback As India Take On Maldives In Friendly','India take on Maldives ahead of their AFC Asian Cup qualifier against Bangladesh.','https://sports.ndtv.com/football/all-eyes-on-sunil-chhetris-comeback-as-india-take-on-maldives-in-friendly-7951680','https://c.ndtvimg.com/2024-06/qb3627bg_sunil-chhetri-afp_625x300_06_June_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:30:50','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(48,'NDTV News','Vikram Bhatt Praises Ibrahim Ali Khan''s Performance In Nadaaniyan','Nadaaniyan released on Netflix on March 7, 2025','https://www.ndtv.com/entertainment/amid-nadaaniyan-criticism-ibrahim-ali-khan-receives-support-from-vikram-bhatt-7951456','https://c.ndtvimg.com/2025-03/vqo2i9t8_nadaaniyan_625x300_18_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 12:26:26','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(49,'NDTV News','''National Team Not About...": Marquez''s Big Take On Chhetris Retirement Return','The Indian senior men''s team will face Maldives in a FIFA International Friendly on Wednesday, March 19 at the Jawaharlal Nehru Stadium in Shillong.','https://sports.ndtv.com/football/national-team-not-about-manolo-marquezs-big-take-on-sunil-chhetris-retirement-return-7952062','https://c.ndtvimg.com/2024-12/5fmp3ako_sunil-chhetri-x-indsuperleague_625x300_07_December_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:23:38','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(50,'NDTV News','Poor Sleep And Male Fertility: Expert Decodes The Link','Studies show that men who sleep for fewer than six hours or more than nine hours every night suffer more from abnormal sperm morphology (form and structure) and motility (movement).','https://doctor.ndtv.com/living-healthy/poor-sleep-and-male-fertility-expert-decodes-the-link-7952203','https://i.ndtvimg.com/i/2018-05/male-infertility_650x400_41525784771.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350','2025-03-18 12:20:17','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(51,'NDTV News','DRDO Scientist Recruitment 2025: Registration Begins, Salary Up To Rs 2.20 Lakh','DRDO Scientist Recruitment 2025: The selection process is solely based on merit, with candidates being ranked according to their performance in the final personal interview.','https://www.ndtv.com/education/drdo-scientist-recruitment-2025-registration-begins-salary-up-to-rs-2-20-lakh-7952187','https://i.ndtvimg.com/i/2017-01/drdo_650x400_51485780531.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:18:28','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(52,'NDTV News','Papad Just Got A Whole Lot More Interesting - Introducing Masala Papad Cups (Recipe Inside)','Masala papad cups are easy to make, packed with flavour, and perfect for those sudden hunger pangs.','https://food.ndtv.com/food-drinks/papad-just-got-a-whole-lot-more-interesting-introducing-masala-papad-cups-recipe-inside-7952184','https://c.ndtvimg.com/2024-05/i0og0oa8_chaat_625x300_21_May_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=675','2025-03-18 12:17:49','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(53,'NDTV News','"Someone Who Lived 300 Years Ago...": Uddhav Thackeray On Aurangzeb Row','Amid violence in Maharashtra&#039;s Nagpur - over demands Mughal ruler Aurangzeb&#039;s grave be moved out of the state - ex-Chief Minister Uddhav Thackeray questioned the need for a face-off, pointing out the Mughal emperor had died over 300 years ago.','https://www.ndtv.com/india-news/aurangzeb-grave-nagpur-violence-uddhav-thackeray-someone-who-lived-300-years-ago-uddhav-thackeray-on-aurangzeb-grave-row-7952166','https://c.ndtvimg.com/2025-03/ugfed8bg_uddhav-thackeray_625x300_05_March_25.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:15:21','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(54,'NDTV News','MasterChef Australia 17 Welcomes Back Indian-Origin Chef Depinder Chhibber','Depinder Chhibber&#039;s previous run on MasterChef Australia was nothing short of spectacular','https://www.ndtv.com/entertainment/masterchef-australia-17-welcomes-back-indian-origin-chef-depinder-chhibber-7950807','https://c.ndtvimg.com/2025-03/lmlr9mkg_depinder_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:14:03','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(55,'NDTV News','Apple Loses German Antitrust Appeal, May Face Tougher Regulations','Apple lost an appeal on Tuesday against a regulatory assessment that opens the iPhone maker up to stricter controls in Germany, the Federal Court of Justice ruled on Tuesday, following years of debate over the company&#039;s market position.','https://www.ndtv.com/world-news/apple-loses-german-antitrust-appeal-may-face-tougher-regulations-7952142','https://c.ndtvimg.com/2025-03/jmd19kng_apple-iphone-_625x300_18_March_25.jpeg','2025-03-18 12:12:13','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(56,'NDTV News','Pak Star Loses Cool After NZ Defeat: "People Are Waiting To See Us Lose..."','Pakistan cricket team fast bowler Haris Rauf lost his cool during the post-match press conference following his team''s defeat against New Zealand in the second T20I encounter.','https://sports.ndtv.com/cricket/pakistan-star-loses-cool-after-new-zealand-defeat-people-are-waiting-to-see-us-lose-7951704','https://c.ndtvimg.com/2025-03/c0p36c6_cs_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:11:50','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(57,'NDTV News','13-Year-Old Suryavanshi To 6 Sixes-Hitter Priyansh: Top 5 IPL 2025 Debutants','The 2025 Indian Premier League (IPL) season is set to introduce a host of new signings, with players from various backgrounds making their debut.','https://sports.ndtv.com/ipl-2025/13-year-old-vaibhav-suryavanshi-to-6-sixes-hitter-priyansh-arya-5-ipl-2025-debutants-to-watch-out-for-7951747','https://c.ndtvimg.com/2024-12/rmm29a54_vaibhav-suryavanshi_625x300_04_December_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 12:01:23','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(58,'NDTV News','Kia Sonet, Seltos, Syros, And Others To Get Price Hike Next Month','Kia India has models like Syros, Sonet, Seltos, Carens, Carnival, EV6, and EV9 in its lineup.','https://www.ndtv.com/auto/kia-sonet-seltos-syros-and-others-to-get-price-hike-next-month-7952008','https://c.ndtvimg.com/2025-03/b9n7u0ro_kia-syros_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=800','2025-03-18 11:57:46','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(59,'NDTV News','Five Uncapped Buys To Look Out For In IPL 2025','This IPL would not be different as plenty of uncapped talent is a part of it and they would be aiming to make a strong impression that could help them climb higher in their careers.','https://sports.ndtv.com/ipl-2025/five-uncapped-buys-to-look-out-for-in-ipl-2025-7948765','https://c.ndtvimg.com/2025-03/rrjha4co_-vaibhav-suryavanshi-is-the-youngest-player-in-ipl_625x300_07_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 11:51:37','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(60,'NDTV News','Telangana Board Class 10 Exam 2025: Where To Check SSC Results Once Declared','TS SSC Class 10 Exam: Candidates are encouraged to visit the MBOSE official website regularly for timely updates on result declarations and other pertinent information.','https://www.ndtv.com/education/telangana-board-class-10-exam-2025-where-to-check-ssc-results-once-declared-7951940','https://c.ndtvimg.com/2022-08/efoop2ug_online-exam-generic_625x300_07_August_22.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 11:47:47','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(61,'NDTV News','"Thousands Crying": Supreme Court Talks Of CBI Probe Into Homeowners'' Troubles','The Supreme Court has expressed concern about the alleged nexus between banks and builders and assured that a probe by the Central Bureau of Investigation will be held into the grievances of homeowners.','https://www.ndtv.com/india-news/thousands-crying-supreme-court-talks-of-cbi-probe-into-homeowners-troubles-7951862','https://c.ndtvimg.com/2024-08/0vu7p2oo_gurugram-apartment-generic_625x300_16_August_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 11:38:52','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(62,'NDTV News','8 Easy Ways To Add Moringa Leaves To Your Diet','Morniga leaves contain powerful antioxidants that help combat oxidative stress in the body.','https://www.ndtv.com/health/8-easy-ways-to-add-moringa-leaves-to-your-diet-7951838','https://c.ndtvimg.com/2024-07/1du6kbn8_moringa-water_625x300_09_July_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 11:34:23','Health','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(63,'NDTV News','S Jaishankar Highlights UN''s Blunder On Kashmir, Calls For New World Order','The injustice done by the West at the UN over Kashmir was highlighted at The Raisina Dialogue - a global multilateral conference held in New Delhi each year.','https://www.ndtv.com/world-news/raisina-dialogue-s-jaishankar-highlights-uns-blunder-on-kashmir-calls-for-reformed-world-order-7951784','https://c.ndtvimg.com/2025-03/v9m86nbs_s-jaishankar-raisina-dialogue-pti_625x300_18_March_25.jpeg','2025-03-18 11:30:03','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(64,'NDTV News','John Abraham''s Car Collection Gets A Stylish New Addition. Details Inside','The dashboard of John Abraham&rsquo;s new car features a unique emblem that proudly reads, &ldquo;MADE FOR JOHN ABRAHAM&rdquo;','https://www.ndtv.com/entertainment/john-abraham-s-car-collection-expands-with-custom-mahindra-thar-roxx-7950153','https://c.ndtvimg.com/2025-03/8jkeepe_john-abraham_625x300_18_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 11:28:25','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(65,'NDTV News','Kim Soo-Hyun''s Upcoming Series Knock-Off Likely To Face Cancellation','Recent K-media reports suggest that rumours are circulating of a potential postponement or even cancellation of the show','https://www.ndtv.com/entertainment/kim-soo-hyun-039-s-disney-series-knock-off-risks-cancellation-amid-kim-sae-ron-dating-controversy-7950128','https://c.ndtvimg.com/2025-03/1nq1fd2g_knockoff_625x300_18_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 11:22:10','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(66,'NDTV News','Parliament Clears Rs 51,463 Crore Extra Spending, Manipur Budget','The Parliament on Tuesday approved the supplementary demands for grants, which entails Rs 51,463 crore additional spending in the current fiscal and the Manipur Budget for 2025-26 with the Rajya Sabha returning four bills to the Lok Sabha.','https://www.ndtv.com/india-news/supplementary-demands-rajya-sabha-parliament-clears-rs-51-463-crore-extra-spending-manipur-budget-7950564','https://c.ndtvimg.com/2023-09/um6j1rso_new-parliament-building_625x300_19_September_23.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 10:31:10','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(67,'NDTV News','No Court Relief For Minister Kapil Mishra In 2020 Poll Code Violation Case','The Delhi High Court on Tuesday refused to stay the trial court proceedings against city Law Minister Kapil Mishra for allegedly making objectionable statements and violating the model code of conduct in 2020.','https://www.ndtv.com/india-news/no-court-relief-for-delhi-minister-kapil-mishra-in-2020-poll-code-violation-case-7951258','https://i.ndtvimg.com/i/2017-05/kapil-mishra-pti_650x400_71495483372.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 10:27:47','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(68,'NDTV News','Ukraine Says Expect Russia To Agree To Ceasefire Ahead Of Trump Call','Ukraine&#039;s foreign minister on Tuesday urged Russia to agree to a 30-day ceasefire proposed by Kyiv and Washington, ahead of a telephone call between Vladimir Putin and Donald Trump.','https://www.ndtv.com/world-news/us-president-donald-trump-russia-vladimir-putin-talks-ukraine-war-7951231','https://c.ndtvimg.com/2025-01/g0k8ilk8_putin-trump-_625x300_23_January_25.jpeg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 10:23:19','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(69,'NDTV News','Lettuce To Vitamins: Sunita Willams And Butch Wilmore''s Experiments In Space','Astronauts Sunita Williams and Butch Wilmore, whose eight-day mission turned into nine months on the International Space Station, are finally heading back to Earth aboard the SpaceX Dragon spacecraft.','https://www.ndtv.com/world-news/space-x-dragon-nasa-homecoming-iss-lettuce-to-vitamins-sunita-willams-and-butch-wilmores-experiments-in-space-7950711','https://c.ndtvimg.com/2025-03/aa5kulq8_sunita-williams-butch-wilmore_625x300_18_March_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 10:20:39','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(70,'NDTV News','This IPL Captain Was A Ball Boy During 2008 Season, Reveals Chat With NZ Great','The inaugural edition of IPL took place in 2008 and Rajasthan Royals emerged as the champions.','https://sports.ndtv.com/ipl-2025/this-ipl-captain-was-a-ball-boy-during-2008-season-reveals-chat-with-new-zealand-great-7950881','https://c.ndtvimg.com/2025-02/oq1nggdo_team-india-bcci-twitter_625x300_20_February_25.jpeg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 10:18:52','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(71,'NDTV News','Can Seed Cycling Fix Irregular Periods Or Hormonal Imbalance? Expert Busts Myths','Seed cycling involves eating flax, pumpkin, sesame and sunflower seeds during different phases of your menstrual cycle.','https://www.ndtv.com/health/can-seed-cycling-fix-irregular-periods-or-hormonal-imbalance-expert-busts-myths-7951154','https://c.ndtvimg.com/2024-06/jaed9kug_nuts-and-seeds_625x300_28_June_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 10:14:50','Health','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(72,'NDTV News','Nukkad Cafe & Bar: A Nostalgic 90s Escape With A Desi Twist Not To Be Missed','Stepping into Nukkad Cafe & Bar felt like walking straight into a Bollywood movie from the 90s.','https://food.ndtv.com/reviews/nukkad-cafe-bar-a-nostalgic-90s-escape-with-a-desi-twist-is-not-to-be-missed-7951076','https://c.ndtvimg.com/2025-03/cg9hdi7_nukkad-cafe-bar_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=675','2025-03-18 10:04:30','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(73,'NDTV News','Volkswagen Golf GTI Spotted In India Ahead Of Launch','Volkswagen Golf GTI is the sportiest version of the hatchback and is powered by a 2.0-litre turbo petrol engine.','https://www.ndtv.com/auto/volkswagen-golf-gti-spotted-in-india-ahead-of-launch-7951026','https://c.ndtvimg.com/2025-03/avq3m7dg_volkswagen-golf-gti_625x300_18_March_25.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=800','2025-03-18 09:59:23','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(74,'NDTV News','"Misleading": Nestle India Slams Fake Job Post Offering Rs 5-10 Lakh Salary','The scam advertises multiple positions with attractive salaries ranging from Rs 5 lakh to Rs 10 lakh per annum.','https://www.ndtv.com/feature/grossly-misleading-nestle-india-debunks-fake-job-post-offering-rs-5-10-lakh-salaries-7951011','https://c.ndtvimg.com/2025-03/lr8s0ob_fake-news_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 09:56:18','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(75,'NDTV News','Mysterious Sea Froth On Australian Beaches Leaves Over 100 Surfers Sick','A mysterious froth has washed up South Australian beaches, raising serious concerns with surfers reportedly falling sick and fish dying in dozens, The Guardian reported.','https://www.ndtv.com/world-news/mysterious-sea-froth-on-australian-beaches-leaves-over-100-surfers-sick-7949295','https://c.ndtvimg.com/2025-03/ac070ihg_australia-beach-froth_625x300_18_March_25.jpeg','2025-03-18 09:53:44','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(76,'NDTV News','"Stay Away From Kuki Referendum Plan": Manipur''s Thadou Tribe Body','The Thadou Inpi Manipur has asked members of their community not to support a &quot;referendum&quot; being considered by a Kuki body to decide whether they want a separate administration carved out from Manipur, or continue living with other communities.','https://www.ndtv.com/india-news/stay-away-from-kuki-referendum-plan-says-thadou-inpi-manipur-7950945','https://c.ndtvimg.com/2023-09/vkl1bcig_churachandpur_625x300_23_September_23.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 09:47:41','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(77,'NDTV News','"Shops Must Display Names In Tamil": Puducherry Amid Language Row','The Chief Minister stated that the government had also decided that all invitations for government department functions should include a Tamil version.','https://www.ndtv.com/india-news/shops-must-display-names-in-tamil-puducherry-chief-minister-amid-language-row-7950905','https://i.ndtvimg.com/i/2016-05/puducherry-chief-minister-n-rangasamy_650x400_41463339070.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 09:40:33','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(78,'NDTV News','Betwa''s Silent Cry: The River That Once Sang Now Struggles For Breath','The catchment areas that once stored water for dry months have been consumed by concrete.','https://www.ndtv.com/india-news/betwas-silent-cry-the-river-that-once-sang-now-struggles-for-breath-7950856','https://c.ndtvimg.com/2025-03/in2sba2_betwa-river-madhya-pradesh_625x300_18_March_25.jpeg?im=FaceCrop,algorithm=dnn,width=1200,height=738','2025-03-18 09:34:41','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(79,'NDTV News','Conan O''Brien Set To Return As Host For Oscars 2026','&quot;The only reason I&#039;m hosting the Oscars next year is that I want to hear Adrien Brody finish his speech,&quot; said Conan O&#039;Brien','https://www.ndtv.com/entertainment/conan-obrien-to-return-as-host-for-oscars-2026-7946146','https://c.ndtvimg.com/2025-03/2gvla02_conan-_625x300_18_March_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 09:34:38','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(80,'NDTV News','PM Modi Praises Maha Kumbh In Parliament, Opposition Raises Questions','Prime Minister Narendra Modi spoke about the Kumbh, but did not pay tribute to those killed in the January 29 stampede at the gathering, Leader of the Opposition Rahul Gandhi said today.','https://www.ndtv.com/india-news/pm-narendra-modi-rahul-gandhi-pm-modi-praises-maha-kumbh-in-parliament-opposition-raises-questions-7950804','https://c.ndtvimg.com/2025-03/9bub3rsg_modi-rahul_625x300_18_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 09:28:43','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(81,'NDTV News','"CCTVs Broken, Vehicles Torched": Residents Share How Nagpur Violence Unfolded','Houses were vandalised and vehicles were torched, recounted the residents of Nagpur, narrating how the violence unfolded last night after calls by a right-wing outfit to remove the tomb of Mughal ruler Aurangzeb.','https://www.ndtv.com/india-news/nagpur-violence-cctvs-broken-vehicles-torched-locals-share-how-violence-unfolded-7950776','https://c.ndtvimg.com/2025-03/hi4m8kc_nagpur-violence-pti_625x300_18_March_25.jpeg','2025-03-18 09:23:25','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(82,'NDTV News','"Visited Temples": Sunita Williams'' Cousin Holds ''Yagna'' For Her Safe Return','Sunita Williams and Barry Wilmore, along with two others, have undocked from the International Space Station (ISS) and are scheduled to splash down soon.','https://www.ndtv.com/india-news/sunita-williams-cousin-holds-yagna-for-her-safe-return-visited-temples-7950775','https://c.ndtvimg.com/2025-03/31573tu8_sunita_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 09:23:05','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(83,'NDTV News','6 Best Parks In Delhi To Soak Up The Spring Season','Pack a picnic, grab a book, or just take a long, leisurely stroll. Whatever you do, make the most of spring 2025 at these gorgeous parks in Delhi.','https://www.ndtv.com/travel/best-parks-in-delhi-for-spring-2025-7950735','https://c.ndtvimg.com/2025-03/fp6q3l8o_lodhi-garden_625x300_18_March_25.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=738','2025-03-18 09:19:29','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(84,'NDTV News','"People They Are Targetting...": KJo Addresses Nadaaniyan Criticism','Karan Johar said, &quot;Words are equally violent&quot;','https://www.ndtv.com/entertainment/karan-johar-addresses-nadaaniyan-criticism-people-they-are-targetting-also-someones-son-daughter-7950712','https://c.ndtvimg.com/2025-03/4s7lk55g_khushi-_625x300_18_March_25.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=738','2025-03-18 09:15:32','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(85,'NDTV News','''Weakened'': Sonia Gandhi Demands Wage Hike Under Rural Employment Scheme','Sonia Gandhi also demanded to abolish the mandatory Aadhaar-based payment system and the National Mobile Monitoring System.','https://www.ndtv.com/india-news/sonia-gandhi-demands-wage-hike-under-rural-employment-scheme-weakened-7950693','https://c.ndtvimg.com/2024-05/nokv1fg8_sonia-gandhi_625x300_13_May_24.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 09:11:10','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(86,'NDTV News','Watch: ''Animal'' Dhoni Breaks The Internet In Advert For Sandeep Reddy Vanga','MS Dhoni turned into ''Animal'' for an advert ahead of the start of IPL 2025.','https://sports.ndtv.com/cricket/ms-dhoni-turns-into-animal-in-advertisement-for-sandeep-reddy-vanga-video-breaks-internet-7950588','https://c.ndtvimg.com/2025-03/52tli298_dhoni-vanga_625x300_18_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 09:01:26','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(87,'NDTV News','"You Remain Close To Our Hearts": PM Modi''s Letter To Sunita Williams','Indian-origin NASA astronaut Sunita Williams today departed for Earth after being stuck on the International Space Station for more than nine months.','https://www.ndtv.com/india-news/looking-forward-to-seeing-you-in-india-pm-modis-letter-to-sunita-williams-7950516','https://c.ndtvimg.com/2025-03/ri9nq4q8_pm-modi-sunita-williams_625x300_18_March_25.jpeg','2025-03-18 08:50:41','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(88,'NDTV News','Top Court Relief For Puja Khedkar, Interim Protection From Arrest Extended','Puja Khedkar is accused of forging her documents to obtain eligibility for the 2022 Union Public Service Commission (UPSC) test.','https://www.ndtv.com/india-news/supreme-court-relief-for-ex-ias-trainee-puja-khedkar-interim-protection-from-arrest-extended-7950478','https://c.ndtvimg.com/2024-07/0bicufq_puja-khedkar_625x300_19_July_24.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 08:47:45','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(89,'NDTV News','Tata YU Fully Autonomous Vehicle Concept Patented In India - Deets','Tata Motors has patented a new fully autonomous vehicle concept called the YU. Here&#039;s all about it.','https://www.ndtv.com/auto/tata-yu-fully-autonomous-vehicle-concept-patented-in-india-deets-7950464','https://c.ndtvimg.com/2025-03/gglssd1o_tata-yu_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=800','2025-03-18 08:43:54','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(90,'NDTV News','"War Is Absurd": Hospitalised Pope Francis Calls To Disarm Earth','Pope Francis called on Tuesday for an end to war around the world in a letter sent from the hospital room where he is recovering from pneumonia.','https://www.ndtv.com/world-news/war-is-absurd-hospitalised-pope-francis-calls-to-disarm-earth-7950459','https://c.ndtvimg.com/2025-03/p3jfs3j_pope-francis-_625x300_14_March_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 08:43:30','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(91,'NDTV News','Yemen''s Houthis Claimed Third Attack On US Warships In 48 hours','The Houthis said on Telegram they had targeted the USS Harry S Truman carrier group with missiles and drones, making the attack the &quot;third in the past 48 hours&quot; in the northern Red Sea.','https://www.ndtv.com/world-news/yemens-houthis-claimed-third-attack-on-us-warships-in-48-hours-7950393','https://c.ndtvimg.com/2025-03/4rlr44tg_yemen-houthi_625x300_18_March_25.jpeg','2025-03-18 08:36:07','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(92,'NDTV News','Sikandar Nache: Salman Khan Dances To The Tune Of Rashmika Mandanna','Sikandar Nache has been choreographed by Ahmed Khan','https://www.ndtv.com/entertainment/sikandar-title-track-sikandar-nache-salman-khan-dances-to-the-tune-of-rashmika-mandanna-7950388','https://c.ndtvimg.com/2025-03/de29ur7_rashmika-_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 08:34:47','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(93,'NDTV News','"Pull My Hair Out": Steyn''s Huge Criticism Of Fast Bowlers, Namedrops Bumrah','Legendary South African pacer Dale Steyn has slammed modern day fast bowlers.','https://sports.ndtv.com/cricket/i-pull-my-hair-out-dale-steyn-makes-huge-criticism-of-fast-bowlers-namedrops-jasprit-bumrah-7946199','https://c.ndtvimg.com/2025-02/5phahmdg_jasprit-bumrah-mohammed-shami_625x300_17_February_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 08:32:58','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(94,'NDTV News','Indian Oil Apprentice Recruitment 2025: Registration Begins, Check Steps To Apply','IOCL Apprentice Recruitment 2025: The selection process is based on merit, with candidates shortlisted according to their percentage of marks in the essential qualification.','https://www.ndtv.com/education/indian-oil-apprentice-recruitment-2025-registration-begins-check-steps-to-apply-7950317','https://c.ndtvimg.com/2022-04/b7galhfo_indian-oil-reuters_625x300_13_April_22.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 08:27:01','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(95,'NDTV News','Rakesh Roshan Confirms Not Directing Hrithik Roshan''s Krrish 4','Latest reports suggest that Krrish 4 has been further delayed because of its astronomical budget','https://www.ndtv.com/entertainment/rakesh-roshan-confirms-not-directing-hrithik-roshans-krrish-4-i-have-to-pass-on-the-baton-7950283','https://c.ndtvimg.com/2025-03/tbn69c9o_krrish-4_625x300_18_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 08:22:25','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(96,'NDTV News','"Evacuate Immediately": Israel''s Warning To Gazans Living Near Border','The Israeli army urged Gazans Tuesday to evacuate areas near the border, after it unleashed a wave of deadly overnight strikes, the most intense since a ceasefire began in January.','https://www.ndtv.com/world-news/evacuate-immediately-israels-warning-to-gazans-living-near-border-7950246','https://c.ndtvimg.com/2025-03/rbc627ao_israel-hamas-war_625x300_18_March_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 08:19:52','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(97,'NDTV News','Aurangzeb''s Unremarkable Tomb Sparks A Massive Storm','Nagpur''s Mahal area witnessed violence and arson last night. Cars were set on fire, stones were thrown and four civilians and over 10 cops were injured','https://www.ndtv.com/india-news/aurangzeb-nagpur-violence-aurangzebs-unremarkable-tomb-sparks-a-massive-storm-7950218','https://c.ndtvimg.com/2025-03/b3lg9i88_aurangzeb_625x300_18_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 08:13:43','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(98,'NDTV News','''Like Sunita Williams, We Will Fight Our Challenges'': Kerala Minister','NASA&#039;s two stuck astronauts headed back to Earth with SpaceX on Tuesday to close out a dramatic marathon mission that began with a bungled Boeing test flight more than nine months ago.','https://www.ndtv.com/india-news/like-sunita-williams-we-will-fight-our-challenges-kerala-finance-minister-k-n-balagopal-7950214','https://c.ndtvimg.com/2025-03/vhu63sd_bala_625x300_18_March_25.jpeg','2025-03-18 08:12:39','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(99,'NDTV News','Harvard Announces Free Tuition For Families Earning $200,000 Or Less A Year','This enhanced financial aid package will take effect at the start of the 2025 academic year.','https://www.ndtv.com/world-news/harvard-announces-free-tuition-to-students-whose-families-earn-less-than-200-000-7950162','https://c.ndtvimg.com/2025-02/dslis5tg_harvard-university_625x300_06_February_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 08:07:19','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(100,'NDTV News','"Being Alive Feels Pretty Cool": Pro Skier Who Survived Toronto Plane Crash','Pete Koukov was one of the 80 survivors of Delta Flight 4819 jet crash-landing in Toronto on February 17.','https://www.ndtv.com/world-news/professional-skier-who-survived-toronto-plane-crash-shares-what-it-was-like-to-be-upside-down-7950161','https://c.ndtvimg.com/2025-03/2r455uro_toronto-plane-crash_625x300_18_March_25.jpeg','2025-03-18 08:06:52','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(101,'NDTV News','D Fadnavis, Deputy E Shinde Call Nagpur Violence A "Planned Conspiracy"','Maharashtra Chief Minister Devendra Fadnavis and his deputy, Eknath Shinde, traded &#039;conspiracy&#039; allegations with the opposition Tuesday, hours after nearly 40 were injured in violence in Nagpur over calls to move Mughal emperor Aurangzeb&#039;s tomb.','https://www.ndtv.com/india-news/aurangzeb-tomb-case-nagpur-violence-conspiracy-devendra-fadnavis-opposition-trade-jabs-7950152','https://c.ndtvimg.com/2025-03/384gfso8_devendra-fadnavis_625x300_18_March_25.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=738','2025-03-18 08:05:20','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(102,'NDTV News','Payal Kapadia Partners With Richa-Ali For Malayalam Film Guptam','Written and directed by Kunjila Mascillamani, Guptam will be presented to investors at the Cin&eacute;V Film Markets in Chandigarh from March 20 to 23','https://www.ndtv.com/entertainment/guptam-payal-kapadia-join-hands-with-richa-chadha-and-ali-fazal-to-produce-kunjila-mascillamani-s-malayalam-film-7949294','https://c.ndtvimg.com/2025-03/ugno7r98_payal-_625x300_18_March_25.jpg?im=FitAndFill,algorithm=dnn,width=1200,height=738','2025-03-18 08:00:32','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(103,'NDTV News','Earthquake Of Magnitude 4.3 Hits Nepal, No Deaths, Damage Reported','The National Earthquake Monitoring and Research Centre said that it recorded the 4.3 magnitude earthquake with its epicentre located at Batulasain of Achham district.','https://www.ndtv.com/world-news/earthquake-of-magnitude-4-3-hits-nepal-no-deaths-damage-reported-7950012','https://c.ndtvimg.com/2024-11/4h4fqblo_earthquake-generic_625x300_28_November_24.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:48:06','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(104,'NDTV News','Shilpa Shetty Performs This Core Strengthening Exercise; 5 Reasons To Add This Exercise To Your Routine','Gliding knee tucks strengthens your upper body, defines your abs, improves posture, lowers back pain and enhances overall stability','https://www.ndtv.com/health/shilpa-shetty-performs-this-core-strengthening-exercises-5-reasons-to-add-this-exercise-to-your-routine-7949982','https://c.ndtvimg.com/2023-12/08edmtog_shilpa-shetty_625x300_17_December_23.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:44:21','Health','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(105,'NDTV News','Kyiv Not An Obstacle For A Peace Deal With Russia: Ukraine Foreign Minister','Ukraine was waiting for clarity to emerge on the peace process after the conversation between Trump and his Russian counterpart Vladimir Putin, expected later on Tuesday, Foreign Minister Andrii said.','https://www.ndtv.com/world-news/kyiv-not-an-obstacle-for-a-peace-deal-with-russia-ukrainian-foreign-minister-andrii-sybiha-7949961','https://c.ndtvimg.com/2025-03/ht3p5ju_russia-ukraine-ceasefire-_625x300_12_March_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:41:42','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(106,'NDTV News','Pakistan-Origin Cricketer, Collapses On Field While Playing, Dies','After fielding for 40 overs and batting for seven, Khan collapsed around 4pm Australian Central Daylight Time (ACDT).','https://sports.ndtv.com/cricket/pakistan-origin-cricketer-dies-after-collapsing-on-field-during-club-match-in-australia-7949825','https://c.ndtvimg.com/2025-03/g2u66p6g_xjunaid-zafar-khan_625x300_18_March_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:34:59','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(107,'NDTV News','This CEO Cancelled 15 Tesla Cars To Buy European EVs. Here''s Why','Mr Roy is growing increasingly frustrated with both Tesla CEO Elon Musk&#039;s statements and the US administration&#039;s environmental policies.','https://www.ndtv.com/world-news/this-ceo-cancelled-15-tesla-cars-to-buy-european-evs-heres-why-7949903','https://c.ndtvimg.com/2025-03/7c9pltoo_mr-roy_625x300_18_March_25.jpeg','2025-03-18 07:31:49','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(108,'NDTV News','"Shocking": Top Court On Trial Courts Denying Bail In "Not Serious Cases"','The Supreme Court said a democratic country must not function like a police state, where law enforcement agencies exercise arbitrary powers to detain individuals without genuine necessity.','https://www.ndtv.com/india-news/supreme-court-on-trial-courts-denying-bail-in-not-very-serious-cases-shocking-7949874','https://c.ndtvimg.com/2025-03/07o74n2_supreme-court_625x300_01_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:30:15','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(109,'NDTV News','IPL 2025: Kolkata Knight Riders SWOT Analysis And Strongest Playing XI','Defending champions Kolkata Knight Riders (KKR) have retained most of their title-winning core as they aim to replicate their success in IPL 2025.','https://sports.ndtv.com/ipl-2025/ipl-2025-kolkata-knight-riders-swot-analysis-and-strongest-playing-xi-kkr-squad-7946515','https://c.ndtvimg.com/2024-05/qt1h7bgg_andre-russell_625x300_27_May_24.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:27:23','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(110,'NDTV News','Opinion: PM Modi''s Latest Podcast Is A Lesson In Tech Outreach','Modi&#039;s efforts to innovate and reinvent political engagement demonstrate his dynamic and ever-evolving approach to connecting with people.','https://www.ndtv.com/opinion/pm-modis-latest-podcast-is-a-lesson-in-tech-outreach-7949848','https://c.ndtvimg.com/2025-03/bis86hso_pm-modi-lex-fridman-ians_625x300_16_March_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:25:53','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(111,'NDTV News','Hero Xtreme 250R, Xpulse 210 Bookings To Open On March 20','Hero Xpulse 210 and the Xtreme 250R were launched at the Bharat Mobility Global Expo 2025.','https://www.ndtv.com/auto/hero-xtreme-250r-xpulse-210-bookings-to-open-on-march-20-7949840','https://c.ndtvimg.com/2025-03/9mbj67fg_hero-xtreme-250r_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=800','2025-03-18 07:23:24','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(112,'NDTV News','Aprilia RSV1100 Trademark Filing Hints V-Twin Supersport''s Revival','Aprilia RSV1100 looks all set to make a comeback to the showroom floors, as the Italian motorcycle manufacturer has got a trademark application filed for the nameplate.','https://www.ndtv.com/auto/aprilia-rsv1100-trademark-filing-hints-v-twin-supersports-revival-7949833','https://c.ndtvimg.com/2025-03/kplbvuf8_apriliarsv1000_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=800','2025-03-18 07:22:52','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(113,'NDTV News','Randeep Hooda Undergoes An Intense Transformation For Jaat With Sunny Deol','Randeep Hooda was last seen in the biographical drama Swatantra Veer Savarkar','https://www.ndtv.com/entertainment/randeep-hooda-undergoes-an-intense-transformation-for-jaat-with-sunny-deol-7949830','https://c.ndtvimg.com/2025-03/8i80rckg_randeep-hooda_625x300_18_March_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:22:06','Entertainment','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(114,'NDTV News','47 People Detained, 14 Cops Injured In Nagpur Violence: Minister','A curfew has been imposed in multiple areas of Nagpur city following tensions over the demand to remove Aurangzeb&#039;s grave.','https://www.ndtv.com/india-news/47-people-detained-at-least-14-cops-injured-in-nagpur-violence-minister-7949814','https://c.ndtvimg.com/2025-03/1p9uiu78_nagpur-_625x300_18_March_25.jpg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:20:33','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(115,'NDTV News','"Maha Kumbh Will Inspire New Achievements": PM Modi In Lok Sabha','Prime Minister Narendra Modi today praised the unity of citizens for making Maha Kumbh, the grand month-long gathering of Hindu pilgrims, a successful event.','https://www.ndtv.com/india-news/maha-kumbh-will-inspire-new-achievements-says-pm-narendra-modi-in-lok-sabha-7949792','https://c.ndtvimg.com/2025-03/5g71i73g_modi-lok-sabha_625x300_18_March_25.jpeg','2025-03-18 07:19:53','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(116,'NDTV News','Customer Gets "Wholesome" Note With Food Order, But Internet Is Suspicious','Viral post: A woman took to Reddit to explain how she was touched to receive a wholesome note along with a meal she ordered online. However, many users questioned its authenticity.','https://food.ndtv.com/news/viral-customer-gets-wholesome-note-with-food-order-but-internet-is-suspicious-7949778','https://c.ndtvimg.com/2025-03/lc8uki5_customer-gets-wholesome-note-with-food-order-but-internet-is-suspicious_625x300_18_March_25.jpg?im=FaceCrop,algorithm=dnn,width=1200,height=675','2025-03-18 07:16:19','General','2025-03-19 20:53:10');
REPLACE INTO "api_news" ("id", "source", "title", "description", "url", "image_url", "published_at", "category", "fetched_at") VALUES
	(117,'NDTV News','Video: Gunman Opens Fire, Snatches Bag With Rs 80 Lakh In Delhi','The incident, caught on CCTV, took place in front of shops on a narrow road in the Lahori Gate area.','https://www.ndtv.com/delhi-news/delhi-robbery-video-gunman-fires-in-air-snatches-bag-with-rs-80-lakh-near-red-fort-7949769','https://c.ndtvimg.com/2025-03/tejngcno_delhi-robbery_625x300_18_March_25.jpeg?im=FeatureCrop,algorithm=dnn,width=1200,height=738','2025-03-18 07:15:35','General','2025-03-19 20:53:10');
UNLOCK TABLES;
/*!40000 ALTER TABLE "api_news" ENABLE KEYS;*/


#
# Table structure for table 'newsdetails'
#

CREATE TABLE /*!32312 IF NOT EXISTS*/ "newsdetails" (
  "Newsid" int(11) NOT NULL AUTO_INCREMENT,
  "newshead" varchar(50) DEFAULT NULL,
  "upload" varchar(50) DEFAULT NULL,
  "category" varchar(50) DEFAULT NULL,
  "Description" varchar(250) DEFAULT NULL,
  PRIMARY KEY ("Newsid")
) AUTO_INCREMENT=6 /*!40100 DEFAULT CHARSET=utf8 COLLATE=utf8_bin*/;



#
# Dumping data for table 'newsdetails'
#

/*!40000 ALTER TABLE "newsdetails" DISABLE KEYS;*/
LOCK TABLES "newsdetails" WRITE;
REPLACE INTO "newsdetails" ("Newsid", "newshead", "upload", "category", "Description") VALUES
	(1,'priya','8975456987','seattlecbe5@gmail.com','cbe');
REPLACE INTO "newsdetails" ("Newsid", "newshead", "upload", "category", "Description") VALUES
	(3,'Exam Results','13.02.2025','Sports','result has released');
REPLACE INTO "newsdetails" ("Newsid", "newshead", "upload", "category", "Description") VALUES
	(4,'india won tas today','2025-02-13','Sports','nil');
REPLACE INTO "newsdetails" ("Newsid", "newshead", "upload", "category", "Description") VALUES
	(5,'Exam Results','2025-02-13','Study','sds');
UNLOCK TABLES;
/*!40000 ALTER TABLE "newsdetails" ENABLE KEYS;*/


#
# Table structure for table 'register'
#

CREATE TABLE /*!32312 IF NOT EXISTS*/ "register" (
  "Regid" int(11) NOT NULL AUTO_INCREMENT,
  "rname" varchar(50) DEFAULT NULL,
  "contact" varchar(50) DEFAULT NULL,
  "email" varchar(50) DEFAULT NULL,
  "Address" varchar(250) DEFAULT NULL,
  "city" varchar(50) DEFAULT NULL,
  "role" varchar(50) DEFAULT NULL,
  "uname" varchar(50) DEFAULT NULL,
  "password" varchar(50) DEFAULT NULL,
  PRIMARY KEY ("Regid")
) AUTO_INCREMENT=5 /*!40100 DEFAULT CHARSET=utf8 COLLATE=utf8_bin*/;



#
# Dumping data for table 'register'
#

/*!40000 ALTER TABLE "register" DISABLE KEYS;*/
LOCK TABLES "register" WRITE;
REPLACE INTO "register" ("Regid", "rname", "contact", "email", "Address", "city", "role", "uname", "password") VALUES
	(4,'sandhya','09876543210','srcw2338b106@srcw.ac.in','neelambur','coimbatore','User','sandhya','123');
UNLOCK TABLES;
/*!40000 ALTER TABLE "register" ENABLE KEYS;*/
/*!40101 SET SQL_MODE=@OLD_SQL_MODE;*/
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;*/
